# Hey Emacs, this is -*- makefile-automake -*- file!
# vim: filetype=automake

ACLOCAL_AMFLAGS = -I $(top_srcdir)/m4

AM_CFLAGS =					\
	$(STD_CFLAGS)

AM_CPPFLAGS =					\
	$(STD_CPPFLAGS)				\
	-include $(top_builddir)/config.h	\
	-I$(srcdir)/include

if HAVE_GSSAPI
AM_CPPFLAGS +=					\
	$(GSSAPI_CFLAGS)
endif

LIBISC_CFLAGS =						\
	-I$(top_srcdir)/include				\
	-I$(top_srcdir)/lib/isc/unix/include		\
	-I$(top_srcdir)/lib/isc/pthreads/include	\
	-I$(top_srcdir)/lib/isc/include			\
	-I$(top_builddir)/lib/isc/include

if HAVE_JSON_C
LIBISC_CFLAGS +=					\
	$(JSON_C_CFLAGS)
endif HAVE_JSON_C

if HAVE_LIBXML2
LIBISC_CFLAGS +=					\
	$(LIBXML2_CFLAGS)
endif HAVE_LIBXML2

if HAVE_READLINE
LIBISC_CFLAGS +=					\
	$(READLINE_CFLAGS)
endif HAVE_READLINE

LIBISC_LIBS = $(top_builddir)/lib/isc/libisc.la

LIBDNS_CFLAGS = \
	-I$(top_srcdir)/lib/dns/include			\
	-I$(top_builddir)/lib/dns/include

LIBDNS_LIBS = \
	$(top_builddir)/lib/dns/libdns.la

if HAVE_DNSTAP
LIBDNS_CFLAGS +=					\
	$(DNSTAP_CFLAGS)
endif HAVE_DNSTAP

if HAVE_LMDB
LIBDNS_CFLAGS +=					\
	$(LMDB_CFLAGS)
endif HAVE_LMDB

LIBNS_CFLAGS = \
	-I$(top_srcdir)/lib/ns/include

LIBNS_LIBS = \
	$(top_builddir)/lib/ns/libns.la

LIBIRS_CFLAGS = \
	-I$(top_srcdir)/lib/irs/include

LIBIRS_LIBS = \
	$(top_builddir)/lib/irs/libirs.la

LIBISCCFG_CFLAGS = \
	-I$(top_srcdir)/lib/isccfg/include

LIBISCCFG_LIBS = \
	$(top_builddir)/lib/isccfg/libisccfg.la

LIBISCCC_CFLAGS = \
	-I$(top_srcdir)/lib/isccc/include/

LIBISCCC_LIBS = \
	$(top_builddir)/lib/isccc/libisccc.la

LIBBIND9_CFLAGS = \
	-I$(top_srcdir)/lib/bind9/include

LIBBIND9_LIBS = \
	$(top_builddir)/lib/bind9/libbind9.la

LIBLTDL_CFLAGS = \
	-I$(top_srcdir)/libltdl

LIBLTDL_LIBS = \
	$(top_builddir)/libltdl/libltdlc.la
