# Hey Emacs, this is -*- makefile-automake -*- file!
# vim: filetype=automake

AM_CPPFLAGS +=					\
	$(CMOCKA_CFLAGS)			\
	-DTESTS_DIR=\"$(abs_srcdir)\"		\
	-DNAMED_PLUGINDIR=\"$(libdir)/named\"

LDADD =			\
	$(CMOCKA_LIBS)
