# Hey Emacs, this is -*- makefile-automake -*- file!
# vim: filetype=automake

AM_CPPFLAGS +=					\
	$(CMOCKA_CFLAGS)			\
	-DNAMED_PLUGINDIR=\"$(libdir)/named\"	\
	-DSKIPPED_TEST_EXIT_CODE=77		\
	-DTESTS_DIR=\"$(abs_srcdir)\"

LDADD =			\
	$(CMOCKA_LIBS)
