.\" $Id: runmdn.1,v 1.3 2000/09/08 05:58:39 ishisone Exp $
.\"
.\" Copyright (c) 2000 Japan Network Information Center.  All rights reserved.
.\"  
.\" By using this file, you agree to the terms and conditions set forth bellow.
.\" 
.\" 			LICENSE TERMS AND CONDITIONS 
.\" 
.\" The following License Terms and Conditions apply, unless a different
.\" license is obtained from Japan Network Information Center ("JPNIC"),
.\" a Japanese association, Fuundo Bldg., 1-2 Kanda Ogawamachi, Chiyoda-ku,
.\" Tokyo, Japan.
.\" 
.\" 1. Use, Modification and Redistribution (including distribution of any
.\"    modified or derived work) in source and/or binary forms is permitted
.\"    under this License Terms and Conditions.
.\" 
.\" 2. Redistribution of source code must retain the copyright notices as they
.\"    appear in each source code file, this License Terms and Conditions.
.\" 
.\" 3. Redistribution in binary form must reproduce the Copyright Notice,
.\"    this License Terms and Conditions, in the documentation and/or other
.\"    materials provided with the distribution.  For the purposes of binary
.\"    distribution the "Copyright Notice" refers to the following language:
.\"    "Copyright (c) Japan Network Information Center.  All rights reserved."
.\" 
.\" 4. Neither the name of JPNIC may be used to endorse or promote products
.\"    derived from this Software without specific prior written approval of
.\"    JPNIC.
.\" 
.\" 5. Disclaimer/Limitation of Liability: THIS SOFTWARE IS PROVIDED BY JPNIC
.\"    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\"    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\"    PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL JPNIC BE LIABLE
.\"    FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\"    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\"    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\"    BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\"    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\"    OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\"    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
.\" 
.\" 6. Indemnification by Licensee
.\"    Any person or entities using and/or redistributing this Software under
.\"    this License Terms and Conditions shall defend indemnify and hold
.\"    harmless JPNIC from and against any and all judgements damages,
.\"    expenses, settlement liabilities, cost and other liabilities of any
.\"    kind as a result of use and redistribution of this Software or any
.\"    claim, suite, action, litigation or proceeding by any third party
.\"    arising out of or relates to this License Terms and Conditions.
.\" 
.\" 7. Governing Law, Jurisdiction and Venue
.\"    This License Terms and Conditions shall be governed by and and
.\"    construed in accordance with the law of Japan. Any person or entities
.\"    using and/or redistributing this Software under this License Terms and
.\"    Conditions hereby agrees and consent to the personal and exclusive
.\"    jurisdiction and venue of Tokyo District Court of Japan.
.\"
.TH MDNCONV 1 "July 7, 2000"
.\"
.SH NAME
runmdn \- A script to allow applications to use multilingual domain names.
.\"
.SH SYNOPSIS
\fBrunmdn\fP \fIprogram-name\fP [\fIargs..\fP]
.\"
.SH DESCRIPTION
.B runmdn
enables applications to use multilingual domain names without recompilation.
Just add ``runmdn'' before the application-name, and the application
can handle non-ASCII domain names.  For example, you can do:
.PP
.RS 4
.nf
\f(CW% runmdn telnet \fInon-ASCII-hostname\fR
.fi
.RE
.PP
Before using runmdn, you should set up properties related to
multilingual DNS by configuring mDNkit's resolver configuration file
\fBmdnres.conf\fP.
See mdnres.conf(5) which describes the configuration.
.\"
.SH IMPLEMENTATION
.B runmdn
is a small shell script that sets up an environment variable called
``LD_PRELOAD'', so that an application dynamically links a shared
library ``libmdnresolv'' before any other shared libraries.
.PP
The library ``libmdnresolv'' provides a special version of some
resolver functions which implement features for handling multilingual
domain names.
.B runmdn
replaces the following functions with the special version:
.PP
.RS 4
.nf
.ft CW
dn_comp
dn_expand
res_hnok
res_ownok
res_mailok
res_dnok
.ft R
.fi
.RE
.PP
These are the crucial functions in resolver library for multilingual
domain name processing.
By overriding them in the standard libraries with the special version
provided by ``libmdnresolv'',
.B runmdn
enables applications to use multilingual domain names.
.RS 4
.IP \(bu 2
Resolver API (such as gethostbyname()) accepts non-ASCII domain names
encoded in the local codeset that the application is using.
Also the result from these APIs may contain non-ASCII domain names.
.IP \(bu 2
The normalization and codeset conversion between application's local
codeset and the codeset used in DNS protocol data are handled
automatically, so users/applications need not worry about them.
.RE
.PP
Properties of multilingual DNS (such as the normalization or the codeset
used on DNS protocol data) can be configured with the mDNkit's
resolver configuration file (
.B mdnres.conf
).  See mdnres.conf(5) for details.
.\"
.SH "BIND 9"
.B runmdn
is designed for BIND4 and BIND8 based resolver libraries.
Since BIND9 introduces a completely different resolver called ``light-weight
resolver'', runmdn cannot be used for applications using BIND9 based resolver.
.PP
Since mDNkit also contains a patch to BIND9 source which makes BIND9
multilingual-aware, use the patch to multilingualize your BIND9 based
resolver.
.SH NOTE
The idea of using ``LD_PRELOAD'' to replace some functions in the standard
library was taken from ``runsocks'' script distributed as part of SOCKS5
reference implementation.
.SH BUGS
There are many cases where
.B runmdn
does not work.
.PP
Your system must support ``LD_PRELOAD'' mechanism in the first place.
.PP
Due to security reasons, ``LD_PRELOAD'' mechanism is disabled for
setuid programs in any sane systems.  So
.B runmdn
does not work for setuid programs such as ping or rsh.
.PP
If your system's resolver is an exotic one that does not use
the functions libmdnresolv provides, you lose.
.SH "SEE ALSO"
mdnres.conf(5), runsocks(1)
