#!/usr/bin/env python3
"""List the merge commits of the current release cycle with their parsed
action/audience tags, and what each one generates.

Cycle boundary: the most recent first-parent commit whose subject matches
"Set up version for BIND" (the version bump that opens the cycle). Override
by passing an explicit <boundary-ref> as argv[1].

Usage:
    scripts/cycle-merges.py [<boundary-ref>] [<tip-ref>]

The audience/action -> changelog/notes mapping is auto-generated by the
project's tooling, so this is a sanity checkmark, not the main event. The
main event is judging whether each tag MATCHES THE SUBSTANCE (see SKILL.md).
"""

# The hyphenated file name is intentional: these are CLI helpers, not
# importable modules.
# pylint: disable=invalid-name
import re
import subprocess
import sys

ACTION_SECTION = {
    "sec": "Security Fixes",
    "new": "New Features",
    "rem": "Removed Features",
    "chg": "Feature Changes",
    "fix": "Bug Fixes",
}
# audience -> (release note?, changelog?)
AUDIENCE = {
    "usr": (True, True),
    "pkg": (True, True),
    "dev": (False, True),
    "test": (False, False),
    "doc": (False, False),
    "ci": (False, False),
    "nil": (False, False),
}
# Subject shape follows the dangerfile's MR_TITLE_RE: optional [9.XX(-S)]
# branch prefix and optional [CVE-...] prefix (backports), then
# action:audience.
SUBJ_RE = re.compile(
    r"^\s*(?:\[[^]]*\]\s*)*"
    r"(sec|new|rem|chg|fix)\s*:\s*(usr|pkg|dev|test|doc|ci|nil)\s*:\s*(.*)$"
)


def git(*args):
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def main():
    boundary = sys.argv[1] if len(sys.argv) > 1 else None
    tip = sys.argv[2] if len(sys.argv) > 2 else "HEAD"
    if boundary is None:
        out = git(
            "log",
            "--first-parent",
            "--grep",
            "Set up version for BIND",
            "-1",
            "--format=%H",
        )
        boundary = out.strip()
        if not boundary:
            sys.exit(
                "could not find a 'Set up version for BIND' commit; pass a boundary ref"
            )
    print(f"# cycle boundary: {boundary[:12]}  tip: {tip}\n")

    raw = git(
        "log", "--merges", "--first-parent", f"{boundary}..{tip}", "--format=%H%x00%s"
    )
    notes = clog = neither = skipped = 0
    for line in raw.splitlines():
        if not line:
            continue
        sha, subj = line.split("\0", 1)
        m = SUBJ_RE.match(subj)
        if not m:
            print(
                f"  SKIP   {sha[:12]}  {subj}   (not an action:audience merge — e.g. tag back-merge)"
            )
            skipped += 1
            continue
        action, audience, _desc = m.groups()
        rn, cl = AUDIENCE[audience]
        gen = "note+changelog" if rn else ("changelog" if cl else "neither")
        if rn:
            notes += 1
        elif cl:
            clog += 1
        else:
            neither += 1
        print(
            f"  {action}:{audience:<4} -> {gen:<14} [{ACTION_SECTION[action]}]  {sha[:12]}  {subj}"
        )

    print(
        f"\n# note+changelog (usr/pkg): {notes}   changelog-only (dev): {clog}"
        f"   neither: {neither}   skipped: {skipped}"
    )
    print(
        "# expected: notes entries == usr/pkg count; reconcile against the generated files."
    )


if __name__ == "__main__":
    main()
