#!/bin/sh

# $Id: reconf,v 1.1.32.1 2008/04/28 04:42:07 marka Exp $

autoreconf
# We do not use automake but we need its install-sh file. We do not 
# care about the exit code.
automake --add-missing || true
