[binaries]
c = 'clang'
# FreeBSD 14 ships Heimdal in the base system, which BIND 9 GSS-API support is
# incompatible with (see https://bugs.freebsd.org/275241), so use the MIT
# Kerberos 5 port instead.
krb5-config = '/usr/local/bin/krb5-config'

[built-in options]
optimization = 'g'

[project options]
line = 'enabled'
