[binaries]
c = 'clang'
# Use MIT Kerberos5 for BIND 9 GSS-API support because of FreeBSD Heimdal
# incompatibility; see https://bugs.freebsd.org/275241.
krb5-config = '/usr/local/bin/krb5-config'

[built-in options]
optimization = 'g'

[project options]
line = 'enabled'
